services:
  nginx:
    image: nginx:alpine
    restart: on-failure
    container_name: "nginx"
    volumes:
      - "./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro,z"
      - "./:/var/www:rw,z"
    ports:
      - "8080:80"
    depends_on:
      - php-fpm
    networks:
      - no-internet

  php-fpm:
    restart: always
    image: "166656354036.dkr.ecr.us-east-1.amazonaws.com/docker-images/php:8.4-fpm-xdebug3.5"
    container_name: "php-fpm"
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
    volumes:
      - "./:/var/www:rw,z"
    depends_on:
      - postgres
    networks:
      - no-internet
      - internet

  postgres:
    image: postgres:18.2-alpine3.22
    container_name: "postgres"
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - "postgres-data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    networks:
      - no-internet
      - internet

  composer:
    image: composer:2.9.5
    container_name: "composer"
    user: "${UID}:${GID}"
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
    volumes:
      - "./:/app:rw,z"
    profiles:
      - ignore
    networks:
      - no-internet
      - internet

volumes:
  postgres-data:

networks:
  no-internet:
    internal: true
    driver: bridge
  internet:
    driver: bridge
