services:
  app:
    image: caddy:2.10-alpine
    restart: on-failure
    container_name: "app"
    volumes:
      - "./docker/app/Caddyfile:/etc/caddy/Caddyfile:ro,Z"
      - "./:/app:ro,Z"
    ports:
      - "8080:80"
    networks:
      - no-internet
      - internet
    depends_on:
      - php-fpm
  php-fpm:
    restart: always
    image: "php-fpm"
    container_name: "php-fpm"
    build:
      context: "./docker"
      dockerfile: php-fpm/Dockerfile
    volumes:
      - "./:/app:rw,Z"
    depends_on:
      - db
    networks:
      - internet
      - no-internet
  db:
    image: postgres:17.5-alpine3.21
    container_name: "db"
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "54321:5432"
    volumes:
      - "db-data:/var/lib/postgresql/data:rw"
    networks:
      - internet
      - no-internet

volumes:
  db-data:

networks:
  no-internet:
    internal: true
  internet:
    internal: false
