version: '3'

dotenv: ['.env']

tasks:
  default:
    cmds: [ task --list ]
    silent: true

  up:
    desc: Start project
    cmd: docker compose up -d

  down:
    desc: Stop project
    cmd: docker compose down --remove-orphans

  composer:
    desc: Run php cli
    cmd: docker compose run --rm composer bash

  ssh:
    desc: SSH into app container
    cmd: docker compose exec -it php-fpm bash
