<?php

declare(strict_types=1);

namespace App\Data\Migration;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260223121834 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE oauth_access_tokens (identifier VARCHAR(100) NOT NULL, expiry_date_time TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_identifier VARCHAR(255) DEFAULT NULL, revoked BOOLEAN NOT NULL, client_identifier VARCHAR(100) NOT NULL, PRIMARY KEY (identifier))');
        $this->addSql('CREATE INDEX IDX_CA42527CE77ABE2B ON oauth_access_tokens (client_identifier)');
        $this->addSql('CREATE TABLE oauth_access_token_scopes (access_token_identifier VARCHAR(100) NOT NULL, scope_identifier VARCHAR(100) NOT NULL, PRIMARY KEY (access_token_identifier, scope_identifier))');
        $this->addSql('CREATE INDEX IDX_9FDF62E98E5675DC ON oauth_access_token_scopes (access_token_identifier)');
        $this->addSql('CREATE INDEX IDX_9FDF62E9E6F8FD99 ON oauth_access_token_scopes (scope_identifier)');
        $this->addSql('CREATE TABLE oauth_auth_codes (identifier VARCHAR(100) NOT NULL, expiry_date_time TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_identifier VARCHAR(255) DEFAULT NULL, redirect_uri VARCHAR(255) DEFAULT NULL, revoked BOOLEAN NOT NULL, client_identifier VARCHAR(100) NOT NULL, PRIMARY KEY (identifier))');
        $this->addSql('CREATE INDEX IDX_BB493F83E77ABE2B ON oauth_auth_codes (client_identifier)');
        $this->addSql('CREATE TABLE oauth_auth_code_scopes (auth_code_identifier VARCHAR(100) NOT NULL, scope_identifier VARCHAR(100) NOT NULL, PRIMARY KEY (auth_code_identifier, scope_identifier))');
        $this->addSql('CREATE INDEX IDX_988BFFBF9A27F5B1 ON oauth_auth_code_scopes (auth_code_identifier)');
        $this->addSql('CREATE INDEX IDX_988BFFBFE6F8FD99 ON oauth_auth_code_scopes (scope_identifier)');
        $this->addSql('CREATE TABLE oauth_clients (identifier VARCHAR(100) NOT NULL, name VARCHAR(255) NOT NULL, redirect_uri JSON NOT NULL, is_confidential BOOLEAN NOT NULL, secret VARCHAR(255) DEFAULT NULL, PRIMARY KEY (identifier))');
        $this->addSql('CREATE TABLE oauth_refresh_tokens (identifier VARCHAR(100) NOT NULL, expiry_date_time TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, revoked BOOLEAN NOT NULL, access_token_identifier VARCHAR(100) NOT NULL, PRIMARY KEY (identifier))');
        $this->addSql('CREATE INDEX IDX_5AB6878E5675DC ON oauth_refresh_tokens (access_token_identifier)');
        $this->addSql('CREATE TABLE oauth_scopes (identifier VARCHAR(100) NOT NULL, PRIMARY KEY (identifier))');
        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, password VARCHAR(255) NOT NULL, roles JSON NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9E7927C74 ON users (email)');
        $this->addSql('ALTER TABLE oauth_access_tokens ADD CONSTRAINT FK_CA42527CE77ABE2B FOREIGN KEY (client_identifier) REFERENCES oauth_clients (identifier) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE oauth_access_token_scopes ADD CONSTRAINT FK_9FDF62E98E5675DC FOREIGN KEY (access_token_identifier) REFERENCES oauth_access_tokens (identifier) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE oauth_access_token_scopes ADD CONSTRAINT FK_9FDF62E9E6F8FD99 FOREIGN KEY (scope_identifier) REFERENCES oauth_scopes (identifier) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE oauth_auth_codes ADD CONSTRAINT FK_BB493F83E77ABE2B FOREIGN KEY (client_identifier) REFERENCES oauth_clients (identifier) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE oauth_auth_code_scopes ADD CONSTRAINT FK_988BFFBF9A27F5B1 FOREIGN KEY (auth_code_identifier) REFERENCES oauth_auth_codes (identifier) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE oauth_auth_code_scopes ADD CONSTRAINT FK_988BFFBFE6F8FD99 FOREIGN KEY (scope_identifier) REFERENCES oauth_scopes (identifier) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE oauth_refresh_tokens ADD CONSTRAINT FK_5AB6878E5675DC FOREIGN KEY (access_token_identifier) REFERENCES oauth_access_tokens (identifier) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE oauth_access_tokens DROP CONSTRAINT FK_CA42527CE77ABE2B');
        $this->addSql('ALTER TABLE oauth_access_token_scopes DROP CONSTRAINT FK_9FDF62E98E5675DC');
        $this->addSql('ALTER TABLE oauth_access_token_scopes DROP CONSTRAINT FK_9FDF62E9E6F8FD99');
        $this->addSql('ALTER TABLE oauth_auth_codes DROP CONSTRAINT FK_BB493F83E77ABE2B');
        $this->addSql('ALTER TABLE oauth_auth_code_scopes DROP CONSTRAINT FK_988BFFBF9A27F5B1');
        $this->addSql('ALTER TABLE oauth_auth_code_scopes DROP CONSTRAINT FK_988BFFBFE6F8FD99');
        $this->addSql('ALTER TABLE oauth_refresh_tokens DROP CONSTRAINT FK_5AB6878E5675DC');
        $this->addSql('DROP TABLE oauth_access_tokens');
        $this->addSql('DROP TABLE oauth_access_token_scopes');
        $this->addSql('DROP TABLE oauth_auth_codes');
        $this->addSql('DROP TABLE oauth_auth_code_scopes');
        $this->addSql('DROP TABLE oauth_clients');
        $this->addSql('DROP TABLE oauth_refresh_tokens');
        $this->addSql('DROP TABLE oauth_scopes');
        $this->addSql('DROP TABLE users');
    }
}
